#!/usr/bin/env bash
#
# One-shot generator for the production .env file. Creates strong random
# secrets for every value the docker-compose stack consumes:
#
#   - BITCOIND_RPCAUTH       (using Bitcoin Core's official rpcauth.py)
#   - BITCOIN_RPC_USER       (literal: "indexer")
#   - BITCOIN_RPC_PASSWORD   (cleartext pair for the rpcauth hash above)
#   - POSTGRES_PASSWORD      (24 hex bytes = 96 bits of entropy)
#   - NODE_SHARED_SECRET     (32 hex bytes = 128 bits of entropy, HMAC key)
#   - NODE_HOSTNAME          (asked interactively; defaults to node.vantagenode.io)
#
# Idempotency: refuses to overwrite an existing .env. If you need to
# regenerate, move the old one out of the way first.
#
# Usage (from the repo root, as the `vn` user):
#   bash infra/setup-env.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "[setup-env] $ENV_FILE already exists. Move it aside first if you want to regenerate."
  exit 1
fi

# Sanity check on tooling
for cmd in python3 openssl curl; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    echo "[setup-env] missing dependency: $cmd"
    exit 1
  fi
done

# Ask for the public hostname (used by Caddy for TLS).
read -r -p "Public hostname (default: node.vantagenode.io): " HOST
HOST="${HOST:-node.vantagenode.io}"

echo "[setup-env] downloading Bitcoin Core's official rpcauth.py..."
RPCAUTH_PY=$(mktemp)
trap 'rm -f "$RPCAUTH_PY"' EXIT
curl -fsSL "https://raw.githubusercontent.com/bitcoin/bitcoin/master/share/rpcauth/rpcauth.py" \
  -o "$RPCAUTH_PY"

BITCOIN_RPC_USER=indexer
BITCOIN_RPC_PASSWORD=$(openssl rand -hex 16)

echo "[setup-env] generating rpcauth hash..."
# rpcauth.py prints 4 lines when a password is supplied:
#   String to be appended to bitcoin.conf:
#   rpcauth=USER:SALT$HASH
#   Your password:
#   <password>
# We grab the rpcauth=... line and strip the prefix.
RPC_OUTPUT=$(python3 "$RPCAUTH_PY" "$BITCOIN_RPC_USER" "$BITCOIN_RPC_PASSWORD")
BITCOIND_RPCAUTH=$(echo "$RPC_OUTPUT" | grep '^rpcauth=' | sed 's/^rpcauth=//')

if [[ -z "$BITCOIND_RPCAUTH" ]]; then
  echo "[setup-env] failed to extract rpcauth from python output:"
  echo "$RPC_OUTPUT"
  exit 1
fi

POSTGRES_PASSWORD=$(openssl rand -hex 24)
NODE_SHARED_SECRET=$(openssl rand -hex 32)

# Observability admin passwords
echo "[setup-env] generating observability passwords..."
GRAFANA_ADMIN_PASSWORD=$(openssl rand -hex 16)
PORTAINER_ADMIN_PASSWORD=$(openssl rand -hex 16)
# Portainer wants its admin password pre-hashed (bcrypt). We use the
# bundled apache2-utils image just for htpasswd -B.
PORTAINER_ADMIN_BCRYPT=$(docker run --rm httpd:2.4-alpine \
  htpasswd -nbB admin "$PORTAINER_ADMIN_PASSWORD" | cut -d ':' -f2)

umask 077
cat > "$ENV_FILE" <<EOF
# Auto-generated by infra/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Mode 0600 — do not commit, do not share.

# ============================================================
# Bitcoin Core
# ============================================================
BITCOIND_RPCAUTH=${BITCOIND_RPCAUTH}
BITCOIN_RPC_USER=${BITCOIN_RPC_USER}
BITCOIN_RPC_PASSWORD=${BITCOIN_RPC_PASSWORD}

# ============================================================
# Postgres
# ============================================================
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# ============================================================
# Indexer API auth (HMAC shared secret)
# Set the same value on the Studio side as VANTAGE_NODE_SECRET.
# ============================================================
NODE_SHARED_SECRET=${NODE_SHARED_SECRET}

# ============================================================
# Public hostname for TLS (Caddy auto-provisions Let's Encrypt)
# ============================================================
NODE_HOSTNAME=${HOST}

# ============================================================
# Observability admin passwords
# ============================================================
PORTAINER_ADMIN_BCRYPT=${PORTAINER_ADMIN_BCRYPT}
GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
EOF

# Print the cleartext passwords ONE TIME so the operator can save them.
echo
echo "==============================================="
echo "  Observability UI credentials — save these!"
echo "==============================================="
echo "  Portainer  → admin / $PORTAINER_ADMIN_PASSWORD"
echo "  Grafana    → admin / $GRAFANA_ADMIN_PASSWORD"
echo "==============================================="

chmod 600 "$ENV_FILE"

echo
echo "[setup-env] wrote $ENV_FILE (mode 0600)."
echo "[setup-env] safe summary (secrets redacted):"
sed 's/=.*/=<REDACTED>/' "$ENV_FILE"
echo
echo "Next steps:"
echo "  1. Point DNS for ${HOST} at this server's IP (65.108.141.77)."
echo "  2. docker compose pull"
echo "  3. docker compose up -d bitcoind"
echo "     (then wait 1-3 days for Initial Block Download)"
echo "  4. After IBD: docker compose up -d   # brings up everything else"
